#
# KeyNanny Makefile
#

.PHONY: doc package version

all:
	@echo "Targets:"
	@echo "make package  - create package"
	@echo "make doc      - recreate README.md from included documentation"
	@echo "make version  - create VERSION file from git tag information"

doc:
	@echo '[//]: # "Autogenerated documentation. Do not edit manually! (hint: make doc)"' >README.md
	@echo '[//]: # "==================================================================="' >>README.md
	pod2markdown bin/keynannyd | grep -A9999 DESCRIPTION >> README.md

version:
	@VERSION_FROM_TAG=`git describe --tags | cut -d- -f1 | perl -p -e 's/.*(\\d+\\.\\d+).*/\\1/g'` ;\
	MINOR_FROM_GIT=`git describe --tags | cut -d- -f2` ;\
	echo "$${VERSION_FROM_TAG}.$${MINOR_FROM_GIT:-0}" >VERSION

package: version
	./make_package.sh
