#
# KeyNanny Makefile
#

.PHONY: doc package

all:
	@echo "Targets:"
	@echo "make package  - create package"
	@echo "make doc      - recreate README.md from included documentation"

doc:
	@echo '[//]: # "Autogenerated documentation. Do not edit manually! (hint: make doc)"' >README.md
	@echo '[//]: # "==================================================================="' >>README.md
	pod2markdown bin/keynannyd | grep -A9999 DESCRIPTION >> README.md

package:
	./make_package.sh

