#!/bin/bash
#
# keynanny start script
#

DAEMON="keynanny"

case "$1" in
    start)
	echo -n "Starting $DAEMON "

	;;
    stop)
	echo -n "Stopping $DAEMON "
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
